apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hms
  namespace: argocd
spec:
  description: Hospital Management System
  sourceRepos:
    - "https://github.com/*/hospital-management-system*"
    - "oci://*"  # ECR OCI registry for Helm charts

  destinations:
    - namespace: hms-production
      server: https://kubernetes.default.svc
    - namespace: hms-staging
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: networking.k8s.io
      kind: IngressClass

  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: apps
      kind: "*"
    - group: autoscaling
      kind: "*"
    - group: policy
      kind: "*"
    - group: networking.k8s.io
      kind: "*"

  orphanedResources:
    warn: true
